// src/utils/split/generatePdf.js
// PDF export for Split Expense module.
// Requires: npm install jspdf jspdf-autotable (already installed for SpendWise)

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const BLUE  = [37, 99, 235];
const GRAY  = [100, 100, 100];
const BLACK = [0, 0, 0];

function header(doc, title) {
  doc.setFontSize(10);
  doc.setTextColor(...GRAY);
  doc.text("SpendWise · Split Expense", 14, 10);
  doc.setFontSize(16);
  doc.setTextColor(...BLACK);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 20);
  doc.setFont("helvetica", "normal");
}

function footer(doc) {
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text(
      `Generated by SpendWise  ·  Page ${i} of ${pages}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: "center" }
    );
  }
}

export function generateSplitPDF({ event, settlements, matrix, summary }) {
  const doc = new jsPDF();
  const participants = event.participants;
  const nameOf = (id) => participants.find((p) => p.id === id)?.name || id;

  // ── Page 1: Summary ────────────────────────────────────────────────────────
  header(doc, event.eventName);

  doc.setFontSize(11);
  doc.setTextColor(...GRAY);
  doc.text("Event Summary", 14, 32);

  autoTable(doc, {
    startY: 36,
    body: [
      ["Event",        summary.eventName],
      ["Participants", participants.map((p) => p.name).join(", ")],
      ["Expenses",     summary.expenseCount],
      ["Grand Total",  `Rs.${summary.grandTotal.toFixed(2)}`],
      ["Largest",      `${summary.largestExpense.name} (Rs.${summary.largestExpense.amount.toFixed(2)})`],
      ["Generated",    new Date(summary.generatedAt).toLocaleString("en-IN")],
    ],
    theme: "grid",
    styles: { fontSize: 10 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 40 } },
    margin: { left: 14, right: 14 },
  });

  // ── Page 2: Expense List ───────────────────────────────────────────────────
  doc.addPage();
  header(doc, "Expense List");

  const expenseRows = event.expenses.map((exp) => {
    const totalPaid = exp.paidBy.reduce((s, p) => s + Number(p.amount), 0);
    const paidByStr = exp.paidBy
      .filter((p) => p.amount > 0)
      .map((p) => `${nameOf(p.participantId)} Rs.${Number(p.amount).toFixed(2)}`)
      .join(", ");

    let sharedByStr;
    if (exp.distributionType === "equal") {
      sharedByStr = exp.sharedBy.map(nameOf).join(", ");
    } else {
      sharedByStr = Object.entries(exp.exactShares)
        .filter(([, v]) => Number(v) > 0)
        .map(([pid, v]) => `${nameOf(pid)} Rs.${Number(v).toFixed(2)}`)
        .join(", ");
    }

    return [
      exp.expenseName,
      exp.distributionType === "equal" ? "Equal" : "Exact",
      paidByStr,
      sharedByStr,
      `Rs.${totalPaid.toFixed(2)}`,
    ];
  });

  autoTable(doc, {
    startY: 28,
    head: [["Expense", "Split", "Paid By", "Shared By", "Total"]],
    body: expenseRows,
    headStyles: { fillColor: BLUE, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: { 4: { halign: "right" } },
    margin: { left: 14, right: 14 },
  });

  // ── Page 3: Settlement ─────────────────────────────────────────────────────
  doc.addPage();
  header(doc, "Settlement");

  if (settlements.length === 0) {
    doc.setFontSize(11);
    doc.setTextColor(...GRAY);
    doc.text("All settled — no transactions needed.", 14, 36);
  } else {
    autoTable(doc, {
      startY: 28,
      head: [["Pays", "→ Receives", "Amount"]],
      body: settlements.map((s) => [nameOf(s.from), nameOf(s.to), `Rs.${s.amount.toFixed(2)}`]),
      headStyles: { fillColor: BLUE, fontStyle: "bold" },
      styles: { fontSize: 10 },
      columnStyles: { 2: { halign: "right" } },
      margin: { left: 14, right: 14 },
    });
  }

  // ── Page 4: Matrix ────────────────────────────────────────────────────────
  doc.addPage();
  header(doc, "Transaction Matrix");

  const matrixHead = ["Pays ↓ / Receives →", ...participants.map((p) => p.name)];
  const matrixBody = participants.map((payer) =>
    [payer.name, ...participants.map((receiver) =>
      payer.id === receiver.id
        ? "-"
        : matrix[payer.id]?.[receiver.id] > 0
          ? `Rs.${matrix[payer.id][receiver.id].toFixed(2)}`
          : ""
    )]
  );

  autoTable(doc, {
    startY: 28,
    head: [matrixHead],
    body: matrixBody,
    headStyles: { fillColor: BLUE, fontStyle: "bold", fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2 },
    margin: { left: 14, right: 14 },
  });

  footer(doc);

  const filename = `${event.eventName.replace(/\s+/g, "-")}-split.pdf`;
  doc.save(filename);
}