// src/utils/notes/notesExportPdf.js
// Export a single note to PDF.

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function exportNoteToPDF(note) {
  const doc = new jsPDF();
  const BLUE = [37, 99, 235];
  const GRAY = [100, 100, 100];

  // Header
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text("SpendWise · Notes", 14, 10);

  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.text(note.title || "Untitled Note", 14, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text(
    `Category: ${note.category}  ·  ${new Date(note.updatedAt).toLocaleString("en-IN")}`,
    14, 29
  );

  // Content — strip HTML tags for plain text
  const plain = (note.content || "")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n")
    .replace(/<\/div>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .trim();

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  const lines = doc.splitTextToSize(plain, 180);
  doc.text(lines, 14, 38);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(
    "Generated by SpendWise",
    doc.internal.pageSize.getWidth() / 2,
    doc.internal.pageSize.getHeight() - 8,
    { align: "center" }
  );

  const filename = `${(note.title || "note").replace(/\s+/g, "-")}.pdf`;
  doc.save(filename);
}
